jardin:
    resource: "@JardinBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

reset:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /personnel/profile